repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-toml
  - id: destroyed-symlinks
  - id: no-commit-to-branch
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: clippy
  - id: fmt
  - id: cargo-check