use clap::{Arg, Command};

#[tokio::main]
async fn main() {
    let cmd = Command::new("bcdown")
        .bin_name("bcdown")
        .subcommand_required(false)
        .subcommand(
            Command::new("login")
                .about("通过cookie或者二维码登录bilibili漫画，如未给出登录方式，则显示当前登录信息")
                .arg(
                    Arg::new("sessdata")
                        .short('s')
                        .long("sessdata")
                        .value_name("SESSDATA")
                        .help("Cookies中的SESSDATA，获取方法见Github")
                        .required(false),
                )
                .arg(
                    Arg::new("qrcode")
                        .short('q')
                        .long("qrcode")
                        .help("通过二维码登录")
                        .required(false),
                ),
        )
        .subcommand(Command::new("info").about("获取工具信息，包括配置信息和缓存信息"))
        .subcommand(Command::new("upgrade").about("升级工具到最新版本"))
        .subcommand(Command::new("list").about("获取本地缓存的漫画列表"))
        .subcommand(
            Command::new("search").about("查找某个漫画").arg(
                Arg::new("id_or_link")
                    .value_name("ID_OR_LINK")
                    .help("漫画的ID或者链接"),
            ),
        )
        .subcommand(subcmd)
        .subcommand(
            Command::new("fetch")
                .about("将漫画下载到缓存目录")
                .arg(
                    Arg::new("id_or_link")
                        .value_name("ID_OR_LINK")
                        .help("漫画的ID或者链接"),
                )
                .arg(
                    Arg::new("range")
                        .value_name("RANGE")
                        .long("range")
                        .short('r')
                        .help("指定下载范围，如1-3,5,7-"),
                ),
        )
        .subcommand(
            Command::new("export")
                .about("导出某个漫画的全部可用章节到pdf文件")
                .arg(
                    Arg::new("id_or_link")
                        .value_name("ID_OR_LINK")
                        .help("漫画的ID或者链接"),
                )
                .arg(
                    Arg::new("format")
                        .value_name("FORMAT")
                        .short('f')
                        .long("format")
                        .help("导出的格式，epub | pdf | zip | plain"),
                )
                .arg(
                    Arg::new("range")
                        .value_name("RANGE")
                        .long("range")
                        .short('r')
                        .help("指定导出范围，如1-3,5,7-"),
                )
                .arg(
                    Arg::new("split")
                        .help("是否每一话输出一个文件，不能与group同时使用")
                        .short('s')
                        .long("split"),
                )
                .arg(
                    Arg::new("output")
                        .long("output")
                        .short('o')
                        .value_name("OUTPUT")
                        .help("输出目录")
                        .required(false),
                )
                .arg(
                    Arg::new("group")
                        .long("group")
                        .short('g')
                        .value_name("GROUP")
                        .required(false)
                        .help("分组导出每组包含的章节数量"),
                ),
        );

    let matches = cmd.get_matches();
    crate::run(matches.subcommand()).await;
}
